### ISSUE TITLE
add icons

### ISSUE THREAD

**Issue by shubhangi-singh21** [shubhangi-singh21/Check-It#3]
Replace icon asset images with icons from the Icons class.
(no need to change the logo)

**Comment by Ruchi101** [comment]
Please assign this to me. I am highly interested.

**Comment by shubhangi-singh21** [comment]
> Please assign this to me. I am highly interested.

@Ruchi101 go ahead! Don't forget to attach your screenshots in the comments while submitting your contributions.

**Comment by navjyot18** [comment]
Can i work on this mam??

**Comment by shubhangi-singh21** [comment]
> Can i work on this mam??

Hi @navjyot18! Will you be comfortable working in Flutter?

**Comment by hiashutoshsingh** [comment]
hey @shubhangi-singh21 I can take this up

**Comment by shubhangi-singh21** [comment]
@hiashutoshsingh go ahead!

**Comment by raziqfarid** [comment]
@shubhangi-singh21 Please assign this to me

**Comment by shubhangi-singh21** [comment]
> @shubhangi-singh21 Please assign this to me

@raziqfarid go ahead!

**Comment by raziqfarid** [comment]
@shubhangi-singh21 Screenshots for the above PR are provided below.

![Screenshot_20201028-125839](https://user-images.githubusercontent.com/7502154/97405982-84a43780-191e-11eb-8def-7d64fbacbefd.png)
![Screenshot_20201028-125816](https://user-images.githubusercontent.com/7502154/97405989-8837be80-191e-11eb-8fd5-b6be272e3136.png)

**Comment by raziqfarid** [comment]
@shubhangi-singh21  Please change the label for the PR(#4 ) raised for this issue from "hactoberfest accepted" to "hactoberfest-accepted"
