### ISSUE TITLE
feat(UI): improve appl UI

### ISSUE THREAD

**Issue by shubhangi-singh21** [shubhangi-singh21/Check-It#5]
Include features like:

- App bar

- Custom UI

- Improved fonts and formatting

**Comment by herocodess** [comment]
Hey there! let me have a go at this issue

**Comment by shubhangi-singh21** [comment]
> Hey there! let me have a go at this issue

sure @herocodess! Don't forget to add your screenshots while submitting your PR.

**Comment by herocodess** [comment]
yeah sure no problem
